name: Deploy to Production Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: "main"
          submodules: "recursive"
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Add credentials
        run: |
          git config user.name "mikilukasik"
          git config user.email "miklosbacsi@gmail.com"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build and push production branch
        run: |
          git checkout -b production
          git reset --hard main

          npm ci
          npm run build

          git add docs
          git commit -m "Build and update docs folder - these are static assets that get deployed to github pages"
          git push -f --set-upstream origin production
