name: Deploy to Production Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: "production"
          submodules: "recursive"
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Add credentials
        run: |
          git config user.name "mikilukasik"
          git config user.email "miklosbacsi@gmail.com"

      - name: Merge main branch
        run: |
          git fetch origin main:main
          git merge main --no-edit --allow-unrelated-histories

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Commit and push changes
        run: |
          git add docs
          git commit -m "Build and update docs folder - these are static assets that get deployed to github pages"
          git push
